//https://github.com/github/fetch
var n="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;function p(){n.Symbol||(n.Symbol=r);p=function(){}}var y=0;function r(d){return"jscomp_symbol_"+d+y++}function z(){p();n.Symbol.iterator||(n.Symbol.iterator=n.Symbol("iterator"));z=function(){}}
(function(d){function m(a){"string"!==typeof a&&(a=String(a));if(/[^a-z0-9\-#$%&'*+.\^_`|~]/i.test(a))throw new TypeError("Invalid character in header field name");return a.toLowerCase()}function v(a){"string"!==typeof a&&(a=String(a));return a}function t(a){var b={next:function(){var b=a.shift();return{done:void 0===b,value:b}}};f.h&&(p(),z(),b[Symbol.iterator]=function(){return b});return b}function c(a){this.map={};a instanceof c?a.forEach(function(a,h){this.append(h,a)},this):a&&Object.getOwnPropertyNames(a).forEach(function(b){this.append(b,
a[b])},this)}function u(a){if(a.bodyUsed)return Promise.reject(new TypeError("Already read"));a.bodyUsed=!0}function w(a){return new Promise(function(b,h){a.onload=function(){b(a.result)};a.onerror=function(){h(a.error)}})}function A(a){var b=new FileReader;b.readAsArrayBuffer(a);return w(b)}function x(){this.bodyUsed=!1;this.g=function(a){this.c=a;if("string"===typeof a)this.b=a;else if(f.blob&&Blob.prototype.isPrototypeOf(a))this.a=a;else if(f.formData&&FormData.prototype.isPrototypeOf(a))this.f=
a;else if(f.searchParams&&URLSearchParams.prototype.isPrototypeOf(a))this.b=a.toString();else if(!a)this.b="";else if(!f.arrayBuffer||!ArrayBuffer.prototype.isPrototypeOf(a))throw Error("unsupported BodyInit type");this.headers.get("content-type")||("string"===typeof a?this.headers.set("content-type","text/plain;charset=UTF-8"):this.a&&this.a.type?this.headers.set("content-type",this.a.type):f.searchParams&&URLSearchParams.prototype.isPrototypeOf(a)&&this.headers.set("content-type","application/x-www-form-urlencoded;charset=UTF-8"))};
f.blob?(this.blob=function(){var a=u(this);if(a)return a;if(this.a)return Promise.resolve(this.a);if(this.f)throw Error("could not read FormData body as blob");return Promise.resolve(new Blob([this.b]))},this.arrayBuffer=function(){return this.blob().then(A)},this.text=function(){var a=u(this);if(a)return a;if(this.a){var a=this.a,b=new FileReader;b.readAsText(a);return w(b)}if(this.f)throw Error("could not read FormData body as text");return Promise.resolve(this.b)}):this.text=function(){var a=u(this);
return a?a:Promise.resolve(this.b)};f.formData&&(this.formData=function(){return this.text().then(B)});this.json=function(){return this.text().then(JSON.parse)};return this}function k(a,b){b=b||{};var h=b.body;if(k.prototype.isPrototypeOf(a)){if(a.bodyUsed)throw new TypeError("Already read");this.url=a.url;this.credentials=a.credentials;b.headers||(this.headers=new c(a.headers));this.method=a.method;this.mode=a.mode;h||(h=a.c,a.bodyUsed=!0)}else this.url=a;this.credentials=b.credentials||this.credentials||
"omit";if(b.headers||!this.headers)this.headers=new c(b.headers);var d=b.method||this.method||"GET",f=d.toUpperCase();this.method=-1<C.indexOf(f)?f:d;this.mode=b.mode||this.mode||null;this.referrer=null;if(("GET"===this.method||"HEAD"===this.method)&&h)throw new TypeError("Body not allowed for GET or HEAD requests");this.g(h)}function B(a){var b=new FormData;a.trim().split("&").forEach(function(a){if(a){var c=a.split("=");a=c.shift().replace(/\+/g," ");c=c.join("=").replace(/\+/g," ");b.append(decodeURIComponent(a),
decodeURIComponent(c))}});return b}function D(a){var b=new c;(a.getAllResponseHeaders()||"").trim().split("\n").forEach(function(a){a=a.trim().split(":");var c=a.shift().trim();b.append(c,a.join(":").trim())});return b}function g(a,b){b||(b={});this.type="default";this.status=b.status;this.ok=200<=this.status&&300>this.status;this.statusText=b.statusText;this.headers=b.headers instanceof c?b.headers:new c(b.headers);this.url=b.url||"";this.g(a)}if(!d.fetch){p();var q;if(q="FileReader"in d&&"Blob"in
d)try{q=!0}catch(a){q=!1}var f={searchParams:"URLSearchParams"in d,h:"Symbol"in d&&"iterator"in Symbol,blob:q,formData:"FormData"in d,arrayBuffer:"ArrayBuffer"in d};c.prototype.append=function(a,b){a=m(a);b=v(b);var c=this.map[a];c||(c=[],this.map[a]=c);c.push(b)};c.prototype["delete"]=function(a){delete this.map[m(a)]};c.prototype.get=function(a){return(a=this.map[m(a)])?a[0]:null};c.prototype.getAll=function(a){return this.map[m(a)]||[]};c.prototype.has=function(a){return this.map.hasOwnProperty(m(a))};
c.prototype.set=function(a,b){this.map[m(a)]=[v(b)]};c.prototype.forEach=function(a,b){Object.getOwnPropertyNames(this.map).forEach(function(c){this.map[c].forEach(function(d){a.call(b,d,c,this)},this)},this)};c.prototype.keys=function(){var a=[];this.forEach(function(b,c){a.push(c)});return t(a)};c.prototype.values=function(){var a=[];this.forEach(function(b){a.push(b)});return t(a)};c.prototype.entries=function(){var a=[];this.forEach(function(b,c){a.push([c,b])});return t(a)};f.h&&(p(),z(),c.prototype[Symbol.iterator]=
c.prototype.entries);var C="DELETE GET HEAD OPTIONS POST PUT".split(" ");k.prototype.clone=function(){return new k(this)};x.call(k.prototype);x.call(g.prototype);g.prototype.clone=function(){return new g(this.c,{status:this.status,statusText:this.statusText,headers:new c(this.headers),url:this.url})};g.error=function(){var a=new g(null,{status:0,statusText:""});a.type="error";return a};var E=[301,302,303,307,308];g.redirect=function(a,b){if(-1===E.indexOf(b))throw new RangeError("Invalid status code");
return new g(null,{status:b,headers:{location:a}})};d.Headers=c;d.Request=k;d.Response=g;d.fetch=function(a,b){return new Promise(function(c,d){var l;l=k.prototype.isPrototypeOf(a)&&!b?a:new k(a,b);var e=new XMLHttpRequest;e.onload=function(){var a=e.status,b=e.statusText,d=D(e),f;f="responseURL"in e?e.i:/^X-Request-URL:/m.test(e.getAllResponseHeaders())?e.getResponseHeader("X-Request-URL"):void 0;c(new g("response"in e?e.response:e.responseText,{status:a,statusText:b,headers:d,url:f}))};e.onerror=
function(){d(new TypeError("Network request failed"))};e.ontimeout=function(){d(new TypeError("Network request failed"))};e.open(l.method,l.url,!0);"include"===l.credentials&&(e.withCredentials=!0);"responseType"in e&&f.blob&&(e.responseType="blob");l.headers.forEach(function(a,b){e.setRequestHeader(b,a)});e.send("undefined"===typeof l.c?null:l.c)})};d.fetch.polyfill=!0}})("undefined"!==typeof self?self:this);
