/* This file was automatically generated.  Do not edit! */
int vec3_exactEquals(float *a,float *b);
void vec3_rotateZ(float *out,float *a,float *b,float c);
void vec3_rotateY(float *out,float *a,float *b,float c);
void vec3_rotateX(float *out,float *a,float *b,float c);
void vec3_transformQuat(float *out,float *a,float *q);
void vec3_transformMat3(float *out,float *a,float *m);
void vec3_transformMat4(float *out,float *a,float *m);
void vec3_bezier(float *out,float *a,float *b,float *c,float *d,float t);
void vec3_hermite(float *out,float *a,float *b,float *c,float *d,float t);
void vec3_lerp(float *out,float *a,float *b,float t);
void vec3_cross(float *out,float *a,float *b);
float vec3_dot(float *a,float *b);
void vec3_normalize(float *out,float *a);
void vec3_inverse(float *out,float *a);
void vec3_negate(float *out,float *a);
float vec3_squaredLength(float *a);
float vec3_length(float *a);
float vec3_squaredDistance(float *a,float *b);
float vec3_distance(float *a,float *b);
void vec3_scaleAndAdd(float *out,float *a,float *b,float scale);
void vec3_scale(float *out,float *a,float b);
void vec3_round(float *out,float *a);
void vec3_max(float *out,float *a,float *b);
void vec3_min(float *out,float *a,float *b);
void vec3_floor(float *out,float *a);
void vec3_ceil(float *out,float *a);
void vec3_divide(float *out,float *a,float *b);
void vec3_multiply(float *out,float *a,float *b);
void vec3_subtract(float *out,float *a,float *b);
void vec3_add(float *out,float *a,float *b);
void vec3_set(float *out,float x,float y,float z);
void vec3_copy(float *out,float *a);
